### ISSUE TITLE
Missing markup for link in index.md

### ISSUE THREAD

**Issue by Kristine1975** [lazyparser/lazyparser.github.io#1]
Hello!

This link in `index.md` has no markup, so it doesn't appear as a link on the web page:
https://github.com/lazyparser/lazyparser.github.io/blob/645c904fc9dad07405dff3a1d185f329a5d59cda/index.md?plain=1#L40
```
https://github.com/lazyparser/weloveinterns
```
it should be:
```
[https://github.com/lazyparser/weloveinterns](https://github.com/lazyparser/weloveinterns)
```

**Comment by lazyparser** [comment]
Thanks! Fixed in d6fbea6cbaf883e42f935383ea672da1845988a6
